import { memo, useCallback } from 'react';
import useEditorStore from '../../../store/useEditorStore';

const TOCViewerSection = memo(function TOCViewerSection() {
  const tocData = useEditorStore(s => s.tocData);
  const tocConfig = useEditorStore(s => s.tocConfig);
  const tocAuto = useEditorStore(s => s.tocAuto);
  const setTOCConfig = useEditorStore(s => s.setTOCConfig);
  const setTOCAuto = useEditorStore(s => s.setTOCAuto);

  const handleLevelToggle = useCallback((level) => {
    if (!tocConfig) return;
    const currentLevels = tocConfig.includeLevels || [];
    let newLevels;
    if (currentLevels.includes(level)) {
      newLevels = currentLevels.filter(l => l !== level);
    } else {
      newLevels = [...currentLevels, level].sort((a, b) => a - b);
    }
    setTOCConfig({ ...tocConfig, includeLevels: newLevels, autoGenerated: false });
  }, [tocConfig, setTOCConfig]);

  const handleRegenerate = useCallback(() => {
    if (!tocData || tocData.length === 0) return;
    const levels = {};
    for (const entry of tocData) {
      levels[entry.level] = (levels[entry.level] || 0) + 1;
    }
    let includeLevels = [1];
    if (levels[1] >= 5) includeLevels = [1];
    else if (levels[1] >= 3 && levels[2] >= 10) includeLevels = [1, 2];
    else if (levels[2] >= 5) includeLevels = [1, 2];
    else if (levels[3] >= 10) includeLevels = [1, 2, 3];
    else {
      const active = Object.keys(levels).map(Number).filter(l => levels[l] > 0);
      includeLevels = active.length > 0 ? active : [1];
    }
    setTOCConfig({
      ...(tocConfig || {}),
      includeLevels,
      autoGenerated: true
    });
  }, [tocData, tocConfig, setTOCConfig]);

  if (!tocData || tocData.length === 0) {
    return (
      <div className="debug-section">
        <div className="debug-section-title">Table of Contents (TOC)</div>
        <div style={{ fontSize: '11px', color: '#888', padding: '4px 0' }}>
          No hay TOC disponible. Carga un libro con encabezados para generar.
        </div>
      </div>
    );
  }

  return (
    <div className="debug-section">
      <div className="debug-section-title">
        Table of Contents (TOC) — {tocData.length} entries
      </div>
      
      <div style={{ marginBottom: '8px', padding: '6px', backgroundColor: '#1a1a2e', borderRadius: '4px' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '6px' }}>
          <label style={{ fontSize: '10px', color: '#888' }}>Auto-TOC:</label>
          <input
            type="checkbox"
            checked={tocAuto}
            onChange={(e) => setTOCAuto(e.target.checked)}
          />
          <span style={{ fontSize: '9px', color: '#666' }}>
            {tocConfig?.autoGenerated ? '(auto-generado)' : '(manual)'}
          </span>
        </div>
        
        <div style={{ display: 'flex', alignItems: 'center', gap: '4px', marginBottom: '4px' }}>
          <span style={{ fontSize: '10px', color: '#888' }}>Niveles:</span>
          {[1, 2, 3, 4, 5, 6].map(level => (
            <button
              key={level}
              onClick={() => handleLevelToggle(level)}
              style={{
                padding: '2px 6px',
                fontSize: '9px',
                backgroundColor: (tocConfig?.includeLevels || []).includes(level) ? '#3498db' : '#333',
                color: (tocConfig?.includeLevels || []).includes(level) ? '#fff' : '#666',
                border: 'none',
                borderRadius: '3px',
                cursor: 'pointer'
              }}
            >
              H{level}
            </button>
          ))}
        </div>
        
        <button
          onClick={handleRegenerate}
          style={{
            padding: '3px 8px',
            fontSize: '9px',
            backgroundColor: '#27ae60',
            color: '#fff',
            border: 'none',
            borderRadius: '3px',
            cursor: 'pointer'
          }}
        >
          Regenerar recomendación
        </button>
      </div>

      <div style={{ maxHeight: '200px', overflowY: 'auto', fontSize: '11px', fontFamily: 'monospace' }}>
        <table style={{ width: '100%', borderCollapse: 'collapse' }}>
          <thead>
            <tr style={{ borderBottom: '1px solid #555', color: '#aaa' }}>
              <th style={{ textAlign: 'left', padding: '2px 4px' }}>Level</th>
              <th style={{ textAlign: 'left', padding: '2px 4px' }}>Title</th>
              <th style={{ textAlign: 'right', padding: '2px 4px' }}>Page</th>
            </tr>
          </thead>
          <tbody>
            {tocData.map((entry, idx) => (
              <tr key={idx} style={{ borderBottom: '1px solid #333' }}>
                <td style={{ padding: '1px 4px' }}>
                  <span style={{
                    backgroundColor: entry.level === 1 ? '#e74c3c' : entry.level === 2 ? '#e67e22' : '#27ae60',
                    padding: '1px 4px',
                    borderRadius: '2px',
                    color: '#fff'
                  }}>
                    H{entry.level}
                  </span>
                </td>
                <td style={{ padding: '1px 4px', paddingLeft: `${(entry.level - 1) * 12 + 4}px` }}>
                  {entry.title.length > 40 ? entry.title.substring(0, 40) + '...' : entry.title}
                </td>
                <td style={{ padding: '1px 4px', textAlign: 'right', color: '#3498db' }}>
                  {entry.page}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
});

export default TOCViewerSection;
