import type { Chapter } from '../types';

export const ENABLE_TOC = true;

export type TOCEntry = {
  title: string;
  level: number;
  chapterIndex: number;
  elementId?: string;
};

export type TOCSeparator = 'dots' | 'dash' | 'none';
export type TOCTemplate = 'classic' | 'balanced' | 'elegant' | 'compact';

// Per-level typography overrides — applied on top of the selected template
export type LevelOverride = {
  fontSize?: string;   // em value, e.g. '0.95em'
  fontWeight?: string; // 'bold' | 'normal'
  indent?: number;     // px
};

export type TOCConfig = {
  includeLevels: number[];
  title: string;
  separator: TOCSeparator;
  template: TOCTemplate;
  digitalLinks: boolean;     // if true, entries are <a> links (for HTML/EPUB)
  levelOverrides: Record<number, LevelOverride>;
  autoGenerated: boolean;
  autoH3FontSize?: string;   // auto-computed uniform H3 font size (not a user override)
  titleTransform?: 'none' | 'sentence' | 'title' | 'upper'; // text capitalization applied at render
  stripLeadingNumber?: boolean; // strip "Capítulo 1 –", "I.", "1." prefixes from entry titles
  addNumbering?: 'none' | 'decimal' | 'roman'; // auto-generate hierarchical numbering at render
};

// ─── Title normalization helpers ─────────────────────────────────────────────

// Matches leading numbering/word-prefix patterns in TOC entry titles, e.g.:
//   "Capítulo 1 – ", "Parte I: ", "Chapter 2. ", "I. ", "1. ", "1 – "
export const TOC_STRIP_NUMBER_RE =
  /^(?:(?:cap[íi]tulo|chap(?:ter)?|parte?|secci[oó]n|ap[eé]ndice|appendix|pr[oó]logo|ep[íi]logo)\s+(?:[IVXLCDM]+|\d+(?:\.\d+)*)\s*[-–—:·.]\s*|[IVXLCDM]{1,6}\s*[-–—:.]\s+|\d+(?:\.\d+)*\s*[-–—:.]\s*)/i;

// Detect which text corrections best fit the extracted TOC entries.
// Returns a partial TOCConfig patch that can be passed directly to patchTOC().
export function detectTitleNormalization(
  entries: TOCEntry[]
): Pick<TOCConfig, 'titleTransform' | 'stripLeadingNumber'> {
  if (!entries || entries.length === 0) return {};

  // Focus on H1 entries as they're most representative of the document's style
  const sample = entries.filter(e => e.level === 1);
  const titles = (sample.length >= 3 ? sample : entries).map(e => e.title);
  if (titles.length === 0) return {};

  // Detect leading number/prefix patterns
  const numberedCount = titles.filter(t => TOC_STRIP_NUMBER_RE.test(t)).length;
  const stripLeadingNumber = numberedCount / titles.length >= 0.3;

  // After potential stripping, analyze capitalization
  const cleanTitles = titles.map(t =>
    stripLeadingNumber ? (t.replace(TOC_STRIP_NUMBER_RE, '').trim() || t) : t
  );

  // Count titles that are ALL CAPS (at least 3 alphabetic characters, all uppercase)
  const allCapsCount = cleanTitles.filter(t => {
    const letters = t.match(/[A-Za-záéíóúüñÁÉÍÓÚÜÑ]/g);
    return letters && letters.length >= 3 &&
      letters.every(c => c === c.toUpperCase() && c !== c.toLowerCase());
  }).length;

  const result: Pick<TOCConfig, 'titleTransform' | 'stripLeadingNumber'> = {};
  if (stripLeadingNumber) result.stripLeadingNumber = true;
  if (allCapsCount / cleanTitles.length >= 0.4) result.titleTransform = 'sentence';
  return result;
}

export const generateRecommendedTOCConfig = (entries: TOCEntry[]): TOCConfig => {
  const levelCounts: Record<number, number> = { 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0 };

  for (const entry of entries) {
    if (levelCounts[entry.level] !== undefined) {
      levelCounts[entry.level]++;
    }
  }

  const h1Count = levelCounts[1];
  const h2Count = levelCounts[2];
  const h3Count = levelCounts[3];

  let includeLevels: number[];

  if (h1Count >= 5) {
    includeLevels = [1];
  } else if (h1Count >= 3 && h2Count >= 10) {
    includeLevels = [1, 2];
  } else if (h2Count >= 5) {
    includeLevels = [1, 2];
  } else if (h3Count >= 10) {
    includeLevels = [1, 2, 3];
  } else {
    const activeLevels: number[] = [];
    for (let i = 1; i <= 6; i++) {
      if (levelCounts[i] > 0) activeLevels.push(i);
    }
    includeLevels = activeLevels.length > 0 ? activeLevels : [1];
  }

  const hasChapterHeaders = entries.some(e =>
    /^(capítulo|chapter|parte|part|sección|section)\s*\d+/i.test(e.title)
  );

  if (hasChapterHeaders && !includeLevels.includes(1)) {
    includeLevels = [1, ...includeLevels];
  }

  // Count how many entries will actually be visible
  const visibleCount = entries.filter(e => includeLevels.includes(e.level)).length;

  // If showing H3 would push visible entries above 40, drop H3 — keeps TOC clean
  if (visibleCount > 40 && includeLevels.includes(3)) {
    includeLevels = includeLevels.filter(l => l < 3);
  }

  // Re-count after possible H3 removal
  const finalCount = entries.filter(e => includeLevels.includes(e.level)).length;

  // Choose template to match content density:
  //   ≤ 12 entries  → elegant   (spacious, dramatic — fits on 1 page with room to breathe)
  //   13–28 entries → classic   (traditional hierarchy — 1–2 pages)
  //   29–50 entries → balanced  (equal weight H1/H2, less vertical gap — 2–3 pages)
  //   51+ entries   → compact   (minimal spacing — keeps a long TOC to 3 pages max)
  let template: TOCTemplate;
  if (finalCount <= 12)      template = 'elegant';
  else if (finalCount <= 28) template = 'classic';
  else if (finalCount <= 50) template = 'balanced';
  else                       template = 'compact';

  return {
    includeLevels,
    title: 'Índice',
    separator: 'dots',
    template,
    digitalLinks: false,
    levelOverrides: {},
    autoGenerated: true
  };
};

// Returns true if text looks like a "nota" or is inside a blockquote — should be skipped.
// Uses \b (word boundary) so "notable" or "notación" don't match.
const isNoteOrQuote = (el: Element): boolean => {
  if (el.tagName.toUpperCase() === 'BLOCKQUOTE') return true;
  if (el.closest('blockquote')) return true;
  const text = el.textContent?.trim() || '';
  return /^nota\b/i.test(text);
};

// Returns true if a <p> element is predominantly bold — acts as an inline subheading.
const isPredominantlyBold = (el: Element): boolean => {
  if (isNoteOrQuote(el)) return false;
  const text = el.textContent?.trim() || '';
  if (!text || text.length < 3) return false;
  const boldText = Array.from(el.querySelectorAll('strong, b'))
    .map(b => b.textContent || '')
    .join('');
  return boldText.length / text.length >= 0.7;
};

export const extractTOC = (chapters: Chapter[]): TOCEntry[] => {
  if (!ENABLE_TOC) return [];

  const entries: TOCEntry[] = [];

  for (let chapterIndex = 0; chapterIndex < chapters.length; chapterIndex++) {
    const chapter = chapters[chapterIndex];
    if (!chapter?.html) continue;

    const tempDiv = document.createElement('div');
    tempDiv.innerHTML = chapter.html;

    const chapterEntries: TOCEntry[] = [];

    // Walk direct children in document order:
    //   - heading tags (H1–H6) → add at their natural level, skip notas
    //   - <p> that is predominantly bold → add as level 3 (inline subheading)
    // Also scan inside wrapper elements (div/section) for nested headings.
    const scan = (container: Element) => {
      for (const child of Array.from(container.children)) {
        const tag = child.tagName.toUpperCase();
        if (/^H[1-6]$/.test(tag)) {
          const level = parseInt(tag.charAt(1), 10);
          const title = child.textContent?.trim() || '';
          if (title && !isNoteOrQuote(child)) {
            chapterEntries.push({ title, level, chapterIndex, elementId: (child as HTMLElement).id || undefined });
          }
        } else if (tag === 'P' && isPredominantlyBold(child)) {
          const title = child.textContent?.trim() || '';
          if (title) {
            chapterEntries.push({ title, level: 3, chapterIndex, elementId: (child as HTMLElement).id || undefined });
          }
        } else if (/^(DIV|SECTION|ARTICLE)$/.test(tag)) {
          scan(child); // recurse into wrappers
        }
      }
    };
    scan(tempDiv);

    // If the chapter has a title but no matching H1 in the HTML, prepend it
    // to THIS chapter's entries only (not the whole array — that was the bug)
    if (chapter.title && chapter.type === 'chapter') {
      const hasMatchingHeading = chapterEntries.some(
        e => e.title.toLowerCase() === chapter.title!.toLowerCase()
      );
      if (!hasMatchingHeading && chapter.title.trim()) {
        chapterEntries.unshift({
          title: chapter.title,
          level: 1,
          chapterIndex,
          elementId: `chapter-${chapter.id}`
        });
      }
    }

    entries.push(...chapterEntries);
  }

  return entries;
};

